CREATE TABLE IF NOT EXISTS work_role (
 role_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 title VARCHAR (50) NOT NULL,
 description VARCHAR (50) NOT NULL,
 salary DOUBLE NOT NULL,
 creation_date DATE NOT NULL
);


